cinit/QAuxiliary

- README.md
- app/src/main/res/values/strings.xml
replace all two `Github` to `GitHub`
null
> misc: fix GitHub spelling

- app/src/main/java/io/github/qauxv/lifecycle/Parasitics.java
修复一个可能的资源注入问题 
经过我的测试在一些内置 Hook 框架中，判断资源成功注入但是依然找不到资源 ID 导致注入失败，经过测试去除资源注入的判断代码，每次重复注入就能成功，而且这样做并未发现其它可能存在的问题，能够正常工作。
> fix: inject module resources maybe problem in some internal Hook Framework

- app/src/main/java/io/github/qauxv/activity/ConfigV2Activity.java
- app/src/main/java/io/github/qauxv/config/SafeModeManager.java
- app/src/main/java/io/github/qauxv/core/MainHook.java
- app/src/main/java/io/github/qauxv/fragment/SettingsMainFragment.kt
- app/src/main/java/io/github/qauxv/fragment/TroubleshootFragment.kt
- app/src/main/java/io/github/qauxv/startup/HookEntry.java
添加新的模块安全模式
之前的安全模式也是通过存储到宿主自身的私有目录 (SharedPreferences/MMKV) 来实现的，一旦模块功能发生错误可能会导致宿主无法启动，甚至不能进入故障排除界面，虽然禁用模块可以解决，但是重新激活模块后**之前错误的配置依然存在**，这种情况在一些**内置 Hook** 或者设备的系统**没有 Root 权限**的情况下**只能清除宿主全部数据**来解决。
新的安全模式采用创建空文件来确定安全模式是否已经开启，空文件的位置创建在宿主在 sdcard 中的 Android/data 私有目录下，在 Android 11 及以上系统可以使用类似 MT 管理器的第三方文件管理器访问这个目录来建立这个文件，这样就可以正常打开宿主并排查相应的错误，避免了需要清除宿主全部数据才能修复的问题。
并且这个方式我也写到模块主界面的故障排除入口对话框上了。
> feat: add new module safe mode

- app/src/main/java/com/hicore/hook/UnlockLeftSlipLimit.java
- app/src/main/java/io/github/qauxv/util/QQVersion.java
方法名H->I
- [1] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [1] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance
> fix:UnlockLeftSlipLimit on QQ 8.9.33 and 8.9.35

- app/src/main/java/cc/ioctl/hook/msg/RevokeMsgHook.java
- app/src/main/java/xyz/nextalone/hook/AutoSendOriginalPhoto.kt
https://github.com/cinit/QAuxiliary/issues/370
> fix: AutoSendOriginalPhoto for QQ 8.9.33+; fix: anti-revoke gray tip not showing for a not-received message

- app/src/main/java/cc/microblock/hook/Pangu.kt
- app/src/main/java/io/github/qauxv/hook/CommonConfigFunctionHook.kt
- app/src/main/java/io/github/qauxv/hook/CommonSwitchFunctionHook.kt
- app/src/main/java/io/github/qauxv/util/dexkit/DexKitTarget.kt
> feat: use Pangu.kt for all settings

- .gitignore
- app/proguard-rules.pro
- app/src/main/java/top/linl/hook/OffRelationshipIdentification.java
- app/src/main/java/top/linl/util/CheckClassType.java
- app/src/main/java/top/linl/util/FieIdUtils.java
- app/src/main/java/top/linl/util/MethodTool.java
- app/src/main/java/top/linl/util/ReflectException.java
add Remove the relationship identifier from the stranger’s profile card ,  realized now top.linl.hook.OffRelationshipIdentification  
add some of my reflection toolity classes ,  realized now top.linl.util  
Please let me know if there are maintenance conflicts for the project
no
> add Remove the relationship identifier from the stranger’s profile card

- app/src/main/java/top/linl/hook/OffRelationshipIdentification.java
- app/src/main/java/top/linl/hook/TurnOffFriendInteractionLogoView.java
#No title
add Turn off friend interaction logo 
no
> add Turn off friend interaction logo

- app/src/main/java/top/linl/hook/FixCleanRecentChat.java
- app/src/main/java/top/linl/util/reflect/ClassUtils.java
- app/src/main/java/top/linl/util/reflect/MethodTool.java
- app/src/main/java/xyz/nextalone/hook/CleanRecentChat.kt
Fix QQNT’s clear recent chat function, I will add it to top/linl/hook/FixCleanRecentChat.java
Add my tool class : top.linl.util.reflect.ClassUtils
xyz.nextalone.hook.CleanRecentChat
> fix : Clean Recent Chat for QQNT

- app/src/main/java/cc/microblock/hook/DumpTelegramStickers.kt
Use `/storage/self/primary` instead of `/storage/emulated/0` to support no-primary user with TGStickerProvider.
> feat: multi-user support for TGStickerProvider

- app/src/main/java/io/github/moonleeeaf/hook/AddEssenceViewerToGroupSettingsHook.java
由于 AndroidIDE Gradle报```SystemInfo is not supported on this operating system```错误，且无法对CI/releases版本的Dex进行合并（打开黑屏，而且无法Hook），因此我无法进行调试
new Java类：```io.github.moonleeeaf.hook.AddEssenceViewerToGroupSettingsHook```
没有了
#673 （我已关闭）
剩余未知
> feat: add EssenceMsgViewer in TroopSettings for TIM 3.5.1 / (TIM 3.5.1) 群设置添加精华消息入口

- app/src/main/java/io/github/moonleeeaf/hook/AddEssenceViewerToGroupSettingsHook.java
对 #817 注解的补充
修改了 AddEssenceViewerToGroupSettingsHook.java 的注解，**引导用户能正常使用功能**
简单测试得知，通过“群机器人”的机器人资料卡可以为 qun.qq.com 添加 p_skey 的 Cookie，因此**这个修改可能会帮助到一些无法正常查看精华的用户**
**再次感谢 klxiaoniu 大佬对本功能的修复和完善以及作者大大的 merge :)**
> Better description for AddEssenceViewerToGroupSettingsHook.java

- app/src/main/java/me/ketal/hook/ChatItemShowQQUin.kt
Adapted to the new layoutid.
Only for 9.0.8. So, none.
> fix: ChatItemShowQQUin for QQ 9.0.8

- app/src/main/java/cc/ioctl/hook/chat/DefaultBubbleHook.java
用 `Class.forName` 代替 `VASMsgBubble.class` 避免 R8 将 `const-class` 前移从而找不到类
#785
> fix: DefaultBubbleHook for lower QQ

- app/src/main/java/me/ketal/hook/ChatItemShowQQUin.kt
Change the supported versions of new ChatItemShowQQUin to QQ 8.9.93.13315+ to supprt QQ 8.9.93~9.0.0 and improve display effect on QQ 9.0.15-
Tested on QQ 8.9.93.13315, 8.9.93, 9.0.0, 9.0.8&9.0.9
> Change the supported versions of new ChatItemShowQQUin to QQ 8.9.93.13315+

- app/src/main/java/me/hd/hook/RemoveCommentAd.kt
修复之前 移除评论广告 hook可能导致空指针闪退的问题
并添加最低版本支持
> fix: RemoveCommentAd bug

- app/src/main/java/cc/ioctl/hook/ui/main/HideMiniAppPullEntry.kt
修复 https://github.com/cinit/QAuxiliary/commit/b7ddb05d3626ef426e0670f6687759600e5f2b28 导致隐藏下拉小程序在低版本上初始化失败的问题
#939
> fix: HideMiniAppPullEntry init failed

- app/src/main/java/com/xiaoniu/hook/UseAioPhotoChoosePanel.kt
> fix: UseAioPhotoChoosePanel for QQ 9.0.55

- app/src/main/java/me/hd/hook/HandleQQSomeFunExit.kt
新增 拦截QQ部分功能闪退[当前支持群礼物] 在 QQ_8_9_88 和 QQ_9_0_56 版本
> feat HandleQQSomeFunExit in QQ_8_9_88/QQ_9_0_56

- app/src/main/java/com/xiaoniu/hook/UseAioPhotoChoosePanel.kt
> fix: UseAioPhotoChoosePanel for QQ 9.0.60

- app/src/main/java/me/hd/hook/HideFriendChatVoice.kt
对聊天右上角的语音图标进行简单隐藏
QQ_8_9_88 和 QQ_9_0_56 混淆(类 方法 变量)都一样，暂不更改
#425
> feat: HideFriendChatVoice(QQ_8_9_88/QQ_9_0_56)

- app/src/main/java/cc/microblock/hook/TimRemoveToastTips.kt
- app/src/main/java/io/github/moonleeeaf/hook/FuckGroupToastTips.kt
1. 将原功能位置移动到 辅助功能 - 群聊
2. 添加专门为 TIM 3.0.0 适配的功能，如题
> feat: remove group toast tip for TIM 3.0.0

- app/src/main/java/cc/microblock/hook/TimRemoveToastTips.kt
com.tencent.mobileqq.activity.aio.rebuild.TroopChatPie$23
> fix: remove another toast in TimRemoveToastTips.kt

- app/src/main/java/io/github/qauxv/util/dexkit/DexKitTarget.kt
- app/src/main/java/xyz/nextalone/hook/AutoReceiveOriginalPhoto.kt
修复 6c60339e6f56dedc11ac1377b6dfe70dfc833dc5 使用的 "com.tencent.qqnt.aio.gallery.part.d" 类在一些版本上不正确的问题
> fix: AutoReceiveOriginalPhoto on QQ 8.9.63+

- app/src/main/java/cc/ioctl/hook/sideswipe/SimplifyQQSettingMe.kt
- app/src/main/java/io/github/qauxv/tlb/QQConfigTable.kt
- app/src/main/java/io/github/qauxv/util/QQVersion.java
> fix: SimplifyQQSettingMe (bottom) on QQ 9.0.85+

- app/proguard-rules.pro
- app/src/main/java/wang/allenyou/hook/DisableUtfControlCharacterInNicknameHook.kt
添加了将 RTLO、LTRO 等 UTF 控制字符替换为空格的功能
添加了将 RTLO、LTRO 等 UTF 控制字符替换为空格的功能。
实现方法为 Hook `TextView` 的 `onPreDraw()` 方法，判断是否有黑名单内字符，如有则将其替换为空格。
预期实现为导致一次重绘，可能有一定性能下降，实际测试符合预期，未有较明显性能下降。
目前已知的问题为回复消息时，显示的被回复内容无法被 Hook 捕捉替换，怀疑为该处采用的 `FasterTextView` 并未继承自 `TextView` 导致。
添加了将 RTLO、LTRO 等 UTF 控制字符替换为空格的功能。
> feat: DisableUtfControlCharacterInNickname

- app/src/main/java/wang/allenyou/hook/DisableUtfControlCharacterInNicknameHook.kt
修复将 RTLO、LTRO 等 UTF 控制字符替换为空格功能会导致无法正常发送消息的问题
对功能实现进行重构，改为 Hook `TextView.onDraw()` 方法，并修正了一个会导致无限循环的错误。
对功能实现进行重构，改为 Hook `TextView.onDraw()` 方法，并修正了一个会导致无限循环的错误。
> fix: DisableUtfControlCharacterInNickname

- app/src/main/java/io/github/leafmoes/RemoveAudioTransition.kt
移除语音面板多余过渡动画
QQ语音面板左右滑动的时候因为这个动画导致UI重影
故写此功能移除这个莫名其妙的动画
> feat:remove audio transition.

- app/src/main/java/top/xunflash/hook/MiniAppDirectJump.kt
1. 小程序/分享卡片跳转APP 支持用户自行配置包名＆正则表达式
2. 新增知乎&小红书&酷安跳转支持
> feat: MiniAppDirectJump supports user self-configuration

- app/src/main/java/io/github/moonleeeaf/hook/FuckOpenContactsActivity.java
FuckOpenContactsActivity - 修复
修改了错误的 Hook 点
正确的hook点:
Lcom/tencent/mobileqq/activity/phone/PhoneMatchActivity;->doOnCreate(Landroid/os/Bundle;)Z
FuckOpenContactsActivity
> fix: FuckOpenContactsActivity

- app/src/main/java/cc/ioctl/hook/msg/ShowMsgCount.kt
- app/src/main/java/io/github/qauxv/util/TIMVersion.java
为 TIM NT 适配 ShowMsgCount
虽然压根没适配到多少()
也就看着 QUIBadge 完全一样才改的控制流(x
如上()
另外修改了此功能的说明
无法进行测试, 理论上更改控制流的部分能正常运行
暂时还不知道()
附件(未被加入到代码中):
```kt
// 一开始写了一坨 后面发现底下有和我要处理的一模一样的功能
// 例如 QUI Badge (下面给的第一个方法签名) 在源代码底下就有
// 为了防止错误的 Hook 减少测试量 这段代码暂时摆在这
if (requireMinTimVersion(TIMVersion.TIM_4_0_98)) {
// 关键词: 99+
// QUI Badge (byd怎么这么多)
// 1. Lcom/tencent/mobileqq/quibadge/QUIBadge;->updateNum(I)V
// 2. …
```
> fix: ShowMsgCount(QUIBadge) on TIM NT 4.0.98

- app/src/main/java/xyz/nextalone/hook/ChatInputHint.kt
聊天框设置提示文本 for TIM NT 4.0.98
添加 Hook 点如下
Lcom/tencent/tim/aio/inputbar/simpleui/TimAIOInputSimpleUIVBDelegate;->B()V
Lcom/tencent/tim/aio/inputbar/simpleui/a;->v()V
未知
> fix: ChatInputHint on TIM_NT 4.0.98

- app/src/main/java/me/hd/hook/TimBarAddEssenceHook.kt
为 TimBarAddEssence 的文字 适配夜间模式
并增大字与按钮间间隔
1. 加大 "精" 与右上角更多之间的间隔
2. 夜间模式时使用白色文字
我真傻, 明明可以直接合并的(?), 我怎么还要再merge到分支一次(x
> ui: night mode text for TimBarAddEssence

- app/proguard-rules.pro
- app/src/main/java/com/enlysure/hook/HideGroupAssistantBanner.kt
- app/src/main/java/xyz/nextalone/hook/SimplifyContactTabs.kt
新增功能：隐藏群助手顶部的 _收进群助手且不提醒_ 的banner （已测试兼容qq nt和tim nt）
修改：让联系人页面精简在tim nt上生效
> feat: hide group assistant banner

- app/src/main/java/io/github/moonleeeaf/hook/HideChatDatabaseCorruptDialogHook.java
导入聊天记录数据库偶遇大粪qQ脑瘫不认库, 每次切换页面关图片弹对话框, 修复未果无法关闭(对话框), 拼尽全力无法憋笑
> feat: HideChatDatabaseCorruptDialog on TIM_NT 4.0.98

- app/src/main/java/cc/ioctl/hook/troop/RemovePlayTogether.kt
> fix: RemovePlayTogether on QQ 8.2.11

- app/src/main/java/io/github/ex3124/hook/BlockBusCard.java
- app/src/main/java/io/github/qauxv/fragment/PendingFunctionFragment.kt
碰到nfc标签时,qq不会再弹出此窗口
在碰到nfc标签时,如果qq不在运行,仍会启动qq,这是因为 com.tencent.mobileqq.activity.JumpActivity 注册了 android.nfc.action.TECH_DISCOVERED , nfc服务会向其发送intent启动它
> feat: BlockBusCard

- app/proguard-rules.pro
- app/src/main/java/im/mingxi/BlockLinkInfo.kt
添加功能"屏蔽链接信息"
屏蔽链接文本消息下方的链接卡片，此功能位于FunctionEntryRouter.Locations.Auxiliary.CHAT_CATEGORY，也许可以提供情绪价值，肯定可以屏蔽耗流量链接。
- [ ✔] 我已经在预期的 QQ 或 TIM 版本上测试了这些更改，并确认它们能够正常工作，不会破坏任何东西（尽我所能）。
- [✔ ] 我的改动不会导致本模块丢失对旧版 QQ 或 TIM 的支持。
- [ ✔] 我已经合并了对后续工作无意义的提交，并确认它们不会对后续维护造成破坏。（必须）
> Added a function BlockLinkInfo

- app/src/main/java/cc/ioctl/hook/troop/TroopFileSaveLasting.kt
- app/src/main/java/cc/ioctl/hook/ui/main/HideMiniAppPullEntry.kt
- app/src/main/java/cc/ioctl/hook/ui/title/RemoveDailySign.kt
- app/src/main/java/com/alphi/qhmk/module/HookUpgrade.java
- app/src/main/java/me/hd/hook/HideMsgListGuild.kt
Fix Something on QQ 9.1.50+
Fixed HideMiniAppPullEntry, TroopFileSaveLasting, HideMsgListGuild, HookUpgrade and RemoveDailySign on QQ 9.1.50 or higher.
TroopFileSaveLasting, HideMsgListGuild, HookUpgrade and RemoveDailySign unavailable
HideMiniAppPullEntry don't eliminate the white screen
> Fix Something on QQ 9.1.50+

- app/src/main/java/me/hd/hook/ChangeGroupStatus.kt
Fix ChangeGroupStatus on QQ 9.1.50+
ChangeGroupStatus is unavailable on QQ 9.1.50.
> Fix ChangeGroupStatus on QQ 9.1.50+

- app/src/main/java/cc/hicore/message/bridge/Nt_kernel_bridge.java
修复表情面板在QQ 9.1.70 上发送图片时崩溃的问题
QQ 貌似在 9.1.70 更新了VASMsgNamePlate，旧的代码会引发 NoSuchMethodError
#1386
> fix: sticker panel on QQ 9.1.70

- app/src/main/java/nep/timeline/MessageUtils.java
Fix feat issue
Fixed the issue where the ptt forward prompt was successful but not sent
> fix: PttForward cannot be forwarded to the group

- app/src/main/java/io/github/nakixii/hook/ForceShowTroopView.kt
Allow users to directly access the chat history of users who have left the group.
> feat: ForceShowTroopView

- app/src/main/java/io/github/horange321/SimplifyQQSettingMe2.kt
侧滑栏精简
新版QQ更改了侧滑栏，所以以前的`侧滑栏精简`功能失效了。
侧滑栏精简
1.  我不知道是哪一个版本起改的侧滑栏，手里也没有旧版QQ用与测试。所以没有加上版本条件限制。
2. 为了保留旧版支持，在设置页面单开了一个选项，而不是改原有的代码。至于区分不同版本不同写法，原因见第一条。如果知道了版本最好将两个设置合并。
3. 不知道怎么缓存 `findField` 结果
> fix: SimplifyQQSettingMe

- app/src/main/java/me/ketal/hook/ChatItemShowQQUin.kt
- app/src/main/java/nep/timeline/PromptForNoSeqMessage.kt
修复开启PromptForNoSeqMessage后ChatItemShowQQUin不工作的问题
修复开启PromptForNoSeqMessage后因为冲突而导致ChatItemShowQQUin不工作
修复开启PromptForNoSeqMessage后ChatItemShowQQUin不工作的问题
> fix: ChatItemShowQQUin is invalid after PromptForNoSeqMessage is enabled
