app/build.gradle.kts

build: only rename release variant outputFileName

---

app/src/main/java/cn/lliiooll/hook/MessageInterception.kt
app/src/main/java/cn/lliiooll/msg/MessageManager.java
app/src/main/java/io/github/qauxv/util/Initiator.java

- [ x] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ x] My code follows the code style of this project
- [ x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

fix MessageInterception

---

app/src/main/java/cn/lliiooll/util/MsgRecordUtil.java

- [ x] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x ] My code follows the code style of this project
- [ x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

add more message type

---

app/src/main/java/cc/ioctl/dialog/RikkaCustomDeviceModelDialog.java
app/src/main/java/com/rymmmmm/hook/CustomDeviceModel.java

- [√] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [√] My code follows the code style of this project
- [√] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

fix CustomDeviceModel

---

app/src/main/java/cc/ioctl/hook/PttForwardHook.java

- [√] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [√] My code follows the code style of this project
- [√] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

fix PttForwardHook

---

app/src/main/java/io/github/qauxv/activity/AppCompatTransferActivity.java
app/src/main/java/io/github/qauxv/activity/SettingsUiFragmentHostActivity.kt
app/src/main/res/layout/main_v2.xml

ui: fix StatusBar

---

app/src/main/java/io/github/qauxv/fragment/PendingFunctionFragment.kt

feat: more pending

---

app/src/main/java/cc/ioctl/hook/RepeaterHook.java

fix: ptt repeat

---

app/src/main/java/io/github/duzhaokun123/hook/MessageTTSHook.kt
app/src/main/java/io/github/qauxv/util/CliOper.java
app/src/main/res/values/ids.xml

long click text message then click TTS to speak out message
none

feat: add text message to speech

---

.github/workflows/pr_ci.yml
.github/workflows/push_ci.yml

ci: ignore docs changes

---

app/src/main/java/io/github/duzhaokun123/hook/MessageTTSHook.kt

fix: typo in TTS description

---

app/src/main/java/me/kyuubiran/hook/AntiUpdate.kt
app/src/main/java/me/kyuubiran/util/ClassHelper.kt

Add AntiUpdate

---

app/src/main/java/me/kyuubiran/hook/AntiUpdate.kt

Fix AntiUpdate

---

app/src/main/java/me/ketal/hook/QWalletNoAD.kt

fix : QWalletNoAD

---

app/src/main/java/me/ketal/hook/FakeBalance.kt

fix: FakeBalance

---

app/src/main/java/cc/ioctl/hook/RepeaterHook.java
app/src/main/java/io/github/qauxv/bridge/ChatActivityFacade.java
app/src/main/java/io/github/qauxv/util/Initiator.java

support repeat  MessageForReplyText and MessageForMixedMsg in QQ_8.5.0 and above.

feat: support more repeat msg type

---

app/src/main/java/com/hicore/QQDecodeUtils/DecodeForEncPic.java
app/src/main/java/me/ketal/hook/PicCopyToClipboard.kt

support copy MessageForMarketFace to Clipboard

feat: support copy MessageForMarketFace to Clipboard

---

app/src/main/java/xyz/nextalone/hook/SimplifyQQSettings.kt

feat: support more item for SimplifyQQSettings

add more item for SimplifyQQSettings

---

app/src/main/java/com/hicore/ReflectUtil/MField.java
app/src/main/java/xyz/nextalone/hook/ChatWordsCount.kt

fix: chat word count for high version QQ

fix: chat word count for high version QQ

---

app/src/main/java/com/hicore/hook/UnlockLeftSlipLimit.java

feat: add Unlock Left Slip Limit
feat: add Unlock Left Slip Limit  
support left slip repeat more msg type

feat: add Unlock Left Slip Limit

---

app/src/main/java/io/github/qauxv/fragment/FuncStatusDetailsFragment.kt

feat: add Screenshot listener in FuncStatusDetailsFragment.kt
feat: add Screenshot listener in FuncStatusDetailsFragment.kt
Prevent users from taking screenshots of logs and display a dialog when detected.

feat: add Screenshot listener in FuncStatusDetailsFragment.kt

---

.github/PULL_REQUEST_TEMPLATE.md

fix: Pull Request Template Spelling mistake
fix: Pull Request Template Spelling mistake

fix: Pull Request Template Spelling mistake

---

app/src/main/java/io/github/duzhaokun123/hook/MessageTTSHook.kt
app/src/main/java/io/github/duzhaokun123/hook/SendTTSHook.kt
app/src/main/java/io/github/duzhaokun123/util/TTS.kt
app/src/main/java/io/github/duzhaokun123/util/TimeFormat.kt
app/src/main/java/io/github/qauxv/router/dispacher/InputButtonHookDispatcher.java
app/src/main/java/io/github/qauxv/util/Initiator.java
app/src/main/res/layout/tts2_dialog.xml
app/src/main/res/values/ids.xml

添加 文字转语音发送
添加 设置 TTS voice
添加 文字转语音发送
添加 设置 TTS voice
none

feat: send tts & text message tts set voice

---

.github/workflows/pr_ci.yml
.github/workflows/push_ci.yml
buildSrc/src/main/kotlin/Version.kt

Build: Update ndk 25

---

app/src/main/java/io/github/qauxv/util/Initiator.java
app/src/main/java/xyz/nextalone/hook/RemoveSuperQQShow.kt

fix: RemoveSuperQQShow on 8.9.5
fix: RemoveSuperQQShow on 8.9.5
#140

 fix: RemoveSuperQQShow on 8.9.5

---

app/src/main/java/io/github/duzhaokun123/hook/GalBgBlurHook.kt
app/src/main/java/io/github/duzhaokun123/util/Windows.kt

feat: grallery background blur

---

app/src/main/java/io/github/duzhaokun123/hook/SendTTSHook.kt

fix: typo in sending TTS

---

.github/workflows/pr_ci.yml
.github/workflows/push_ci.yml

update deprecated actions

---

app/src/main/java/io/github/qauxv/fragment/SettingsMainFragment.kt
app/src/main/java/me/singleneuron/util/EasterEggsForTheNonexistent.kt

(Not tested, CI can't run for my fork)
- The transgender emoji is also common and the transgender flag emoji includes it
- The "fish cake with swirl" emoji is also widely used among Chinese MtFs/MtXs
N/A

misc: update easter egg emojis

---

app/src/main/java/cc/ioctl/hook/notification/NewQNotifyEvolution.kt

reply in notification & optimize logic

---

app/src/main/java/cc/ioctl/hook/notification/NewQNotifyEvolution.kt

feat: avatar in NewQNotifyEvo

---

app/src/main/java/io/github/qauxv/config/SafeModeManager.java
app/src/main/java/io/github/qauxv/fragment/TroubleshootFragment.kt
app/src/main/java/io/github/qauxv/startup/HookEntry.java

修复安全模式在 MIUI 上宿主包名错误问题
会出现：com.miui.catcherpatch

fix: safe mode maybe got wrong package name in MIUI and add enable/disable fail prompts

---

app/src/main/java/me/ketal/hook/MultiActionHook.kt

to increase success rate.
#227

Add sleep for batch recall

---

app/src/main/java/com/xiaoniu/hook/DisableAddTroopToRecentUser.kt
app/src/main/java/com/xiaoniu/hook/DisableTroopGuild.kt

feat: DisableTroopGuild; DisableAddTroopToRecentUser

---

app/src/main/java/me/ketal/hook/MultiActionHook.kt

fix: crash when batch recall is clicked more than once

---

app/src/main/java/me/qcuncle/hook/TranslateTextMsg.kt
app/src/main/res/values/ids.xml

feat: add hook for text message translation
Thank you, Gu Guhua! success!

feat: add hook for text message translation

---

app/src/main/java/cc/ioctl/hook/ui/profile/DisableAvatarDecoration.java

fix: DisableAvatarDecoration and optimize code

---

app/proguard-rules.pro
app/src/main/java/com/codepwn/hook/ForceEnableQQSettingMeV9.kt

feat: ForceEnableQQSettingMeV9

---

README.md

docs: simplify clone repo steps

---

app/src/main/java/cc/microblock/hook/ForceEnableMultiForward.kt

feat: impl force multi forward

---

app/src/main/java/cc/ioctl/hook/sideswipe/SimplifyQQSettingMe.kt
app/src/main/java/io/github/qauxv/hook/CommonConfigFunctionHook.kt
app/src/main/java/io/github/qauxv/util/dexkit/DexKitTarget.kt
app/src/main/java/xyz/nextalone/base/MultiItemDelayableHook.kt

Fixed some problems with the purification list.
Fixed some problems with the purification list.
Fixed some problems with the purification list.

Fixed some problems with the purification list.

---

app/src/main/java/cc/ioctl/hook/sideswipe/SimplifyQQSettingMe.kt

Fix NPE caused by purifying sideswipe.

---

app/src/main/java/top/linl/hook/FixCleanRecentChat.java
app/src/main/java/xyz/nextalone/hook/CleanRecentChat.kt

Fixed crash caused by adding and deleting viewHolderList, fixed by replacing with ConcurrentHashMap
Fixed the modal pop-up window that includes the selection of group chat, other chats, all chats, including pinned chats, and can now be used normally.

fix: Clean Recent Chat - DeleteMode : including group chat, other chat, topChat

---

app/src/main/java/io/github/qauxv/startup/StartupHook.java

Fix Startup on QQ 9.0.8.14600.
io.github.qauxv.startup.StartupHook

fix: Startup on QQ 9.0.8.14600

---

app/src/main/java/top/linl/hook/FixCleanRecentChat.java
app/src/main/java/top/linl/hook/OffRelationshipIdentification.java
app/src/main/java/top/linl/hook/SortTroopSettingAppListView.java
app/src/main/java/top/linl/hook/TurnOffFriendInteractionLogoView.java
app/src/main/java/top/linl/util/reflect/ClassUtils.java
app/src/main/java/top/linl/util/reflect/FieldUtils.java
app/src/main/java/top/linl/util/reflect/MethodTool.java

I fix QQ9+ short troop setting appinfo 
change field tool class name
If compilation fails, try cleaning the build folder
I do no know
top.linl.hook.*
top.linl.util.ClassUtils
top.linl.util.MethodTool
top.linl.util.FieldUtils

fix : sort troop setting app info , for QQ9.0.0+

---

app/src/main/java/cc/ioctl/hook/misc/CustomDeviceModel.java
app/src/main/res/layout/rikka_custom_device_model_dialog.xml

New hookclass updated.
Tested on QQ 8.9.90 and 9.0.8. (Theoretically supports more versions.)
#174 (maybe)

fix: CustomDeviceModel

---

app/src/main/java/cc/ioctl/hook/chat/DefaultFont.java
app/src/main/java/cc/ioctl/hook/ui/profile/DisableAvatarDecoration.java

use lazy class instead of class ref to fix ClassNotFoundException in release ver
N/A

fix: hooker DefaultFont and AvatarDecoration for lower QQ

---

app/src/main/java/com/alphi/qhmk/module/HiddenVipIconForSe.java
app/src/main/java/io/github/fusumayuki/hook/HideQQValue.kt

隐藏侧滑栏与资料卡上的 QQ 能量值
Tested on QQ 8.9.90~9.0.35.16215 & QQ 8.9.63
#838 (Partially)

feat: add HideQQValue

---

app/src/main/java/cc/ioctl/hook/qzone/HideQZMTitleBarEntrance.kt

Adapted to the new QZoneFeedxTopEntrance
Tested on QQ 9.0.8~9.0.35.16215 & QQ 8.9.63

Fix: HideQZMTitleBarEntrance

---

app/src/main/java/cc/ioctl/hook/ui/main/HideMiniAppPullEntry.kt

fix: HideMiniAppPullEntry white screen

---

.github/workflows/pr_ci.yml
.github/workflows/push_ci.yml
app/proguard-rules.pro
app/src/main/java/io/github/fusumayuki/hook/HideQZoneGuidePublishMoodBanner.kt
gradle/libs.versions.toml

 feat: add HideQZoneGuidePublishMoodBanner

---

app/src/main/java/me/hd/hook/RemoveCommentAd.kt

feat: add RemoveCommentAd

---

app/src/main/java/me/hd/hook/ChangeGroupStatus.kt

feat: add ChangeGroupStatus

---

app/src/main/java/cc/ioctl/hook/ui/main/HideMiniAppPullEntry.kt

修复 QQ 9.0.50 Beta 上隐藏下拉小程序坏掉的问题

fix: HideMiniAppPullEntry on QQ 9.0.50

---

.github/workflows/pr_ci.yml
.github/workflows/push_ci.yml
app/src/main/java/xyz/nextalone/hook/SimplifyPlusPanel.kt
app/src/main/java/xyz/nextalone/hook/SimplifyQQSettings.kt

修复 QQ 9.0.30+ "精简设置菜单" 中的 "免流量" 坏掉的问题
"精简加号菜单" 添加 "短视频" 选项
合并 [renovate](https://github.com/cinit/QAuxiliary/commit/c3cfc1affd92c3a6c547ded726e94f2d8a29a1a2) 对依赖的更新 (#930)

Fix SimplifyQQSettings (CUOpenCard) on QQ 9.0.30+, SimplifyPlusPanel add ShortVideo

---

app/src/main/java/io/github/qauxv/util/dexkit/DexKitTarget.kt
app/src/main/java/me/hd/hook/FakePhone.kt

feat: add FakePhone

---

app/src/main/java/cc/ioctl/hook/msg/PicMd5Hook.java

修复: PicMd5Hook 中的 getPicturePath
Make getPicturePath in PicMd5Hook Great Again!
#921

fix: getPicturePath in PicMd5Hook

---

app/src/main/java/me/hd/hook/FakePhone.kt

fix: FakePhone(9.0.25-5942)

---

app/src/main/java/com/alphi/qhmk/module/HookQWallet.java
app/src/main/java/me/hd/hook/DisableSwipeRight.kt
app/src/main/java/me/hd/hook/FakeLocation.kt
app/src/main/java/me/hd/hook/FakePhone.kt
app/src/main/java/me/hd/hook/HideClockInTip.kt

fix: HookQWallet 修复 隐藏QQ钱包超值精选 功能导致红包功能异常的问题 #697
fix: HideClockInTip 更改 隐藏打卡提示 中相关代码注释
fix: FakePhone 更改 伪装手机号码 中相关代码注释
feat: FakeLocation(8.9.88-4852) 新增 虚拟群聊内共享位置定位内容 #103
feat: DisableSwipeRight(8.9.88-4852) 新增 屏蔽聊天右滑显示界面[群聊|群应用][好友|亲密关系]
#697
#103

fix(HookQWallet) and feat(FakeLocation,DisableSwipeRight)

---

app/src/main/java/io/github/qauxv/util/data/ContactDescriptor.java

fix: Ptt Multi Forward(8.9.88-4852)

---

app/src/main/java/me/hd/hook/HideTroopToDo.kt

feat: HideTroopToDo(8.9.88-4852)

---

app/src/main/java/cc/ioctl/hook/experimental/CardMsgSender.java

更改了卡片消息的发送逻辑，使其能够及时显示已发送的卡片消息。
原先发送方式在私聊的时候不会在发送后显示已发送的卡片消息，需要退出聊天窗口刷新后再进入才可看到。群聊虽然无此类问题，但发送成功后也是会停顿一会再显示。另外，原先发送卡片后按钮状态不会改变，现在在发送成功后也一并修改了按钮的状态。

fix: CardMsgSender where PM card messages were not displaying

---

app/src/main/java/me/hd/hook/HideTroopToDo.kt

fix: HideTroopToDo(9.0.25-5932)

---

app/src/main/java/me/hd/hook/ChangeFriendsVip.kt
app/src/main/java/me/hd/hook/FakePhone.kt
app/src/main/java/me/hd/hook/FakeVoiceTime.kt

新增 更改好友会员 ( 相当于 [隐藏会员红名] + [联系人排序] )
重构 伪装手机号码，伪装语音时间

feat(ChangeFriendsVip) and refactor (FakePhone,FakeVoiceTime)

---

app/src/main/java/me/hd/hook/ChangeCircleJumpProfile.kt
app/src/main/java/me/hd/hook/FakeLocation.kt

feat(ChangeCircleJumpProfile) and refactor(FakeLocation)

---

app/src/main/java/cc/hicore/Utils/FileUtils.java

fix StickerPanel delete bug

---

app/src/main/java/io/github/qauxv/util/dexkit/DexKitTarget.kt
app/src/main/java/me/hd/hook/FakePhone.kt
app/src/main/java/me/hd/hook/HideClockInTip.kt
app/src/main/java/me/hd/hook/HideTroopToDo.kt
app/src/main/java/me/hd/hook/RemoveSelectedMedia.kt

使用DexKit重构 伪装手机号码，适配更多版本
移除部分注释
#981

refactor FakePhone

---

app/src/main/java/io/github/qauxv/util/QQVersion.java

chore: update QQ versionCode

---

app/src/main/java/cc/microblock/hook/ImageCustomSummary.kt

适配 图片/表情包附加自定义概要 QQ_9_0_56
#991

fix ImageCustomSummary in QQ_9_0_56

---

app/src/main/java/io/github/qauxv/util/dexkit/DexKitTarget.kt
app/src/main/java/me/hd/hook/HandleQQSomeFunExit.kt

add fixFileView in HandleQQSomeFunExit

---

app/src/main/java/cc/ioctl/dialog/RikkaBaseApkFormatDialog.java
app/src/main/java/cc/ioctl/hook/file/BaseApk.java
app/src/main/res/layout/rikka_base_apk_dialog.xml

重命名APK 添加正則匹配

---

app/proguard-rules.pro
app/src/main/java/com/xiaoniu/dispatcher/MenuBuilderHook.kt
app/src/main/java/top/xunflash/hook/MiniAppDirectJump.kt
app/src/main/res/drawable/ic_item_open_72dp.xml
app/src/main/res/values/ids.xml

长按小程序/分享卡片增加直接打开APP的菜单项，省去打开卡顿的小程序/网页的步骤（暂时仅支持哔哩哔哩）
（（回滚失误不小心把pr给close了，顺便直接把嵌套的if改了，另外其他两个问题是从qa里面抄的代码，应该问题不大吧（？

feat: add MiniAppDirectJump

---

app/src/main/java/top/xunflash/hook/MiniAppDirectJump.kt

fix: open share url directly by app

---

app/src/main/java/io/github/memory2314/hook/GuildOldStyle.kt

添加频道旧版样式
[#794](https://github.com/cinit/QAuxiliary/issues/794)

feat: GuildOldStyle

---

app/src/main/java/io/github/memory2314/hook/RemoveShareLimit.kt

feat: RemoveShareLimit

---

app/src/main/java/io/github/qauxv/fragment/TroubleshootFragment.kt

Add debugging func: open the specified activity.

---

app/src/main/java/cc/ioctl/hook/experimental/FileRecvRedirect.kt
app/src/main/java/cc/microblock/hook/Pangu.kt

fix pangu and optimize FileRecvRedirec logic 

---

app/src/main/java/me/singleneuron/util/EasterEggsForTheNonexistent.kt

Pride for nextalone

---

app/src/main/java/cc/ioctl/hook/msg/ShowMsgCount.kt

fix: revise ShowMonsCount description

---

app/src/main/java/awoo/linwenxuan04/hook/ChannelProxyHook.kt

为 拦截trpc.o3.*包 添加一条警告
按照频道内提示, 添加此警告
无

chore: add warnings in ChannelProxyHook.kt

---

app/src/main/java/cc/hicore/hook/UploadTransparentAvatar.java
app/src/main/java/cc/ioctl/hook/msg/MultiForwardAvatarHook.kt
app/src/main/java/cc/ioctl/hook/msg/ShowMsgCount.kt
app/src/main/java/com/xiaoniu/hook/DisableReactionLimit.kt
app/src/main/java/io/github/qauxv/util/dexkit/DexFlow.java

Fix components to support QQ 9.1.50

fix: fix support for QQ 9.1.50

---

app/src/main/java/com/alphi/qhmk/module/HookUpgrade.java

fix: HookUpgrade on QQ 8.2.11

---

app/src/main/java/cc/ioctl/hook/sideswipe/SimplifyQQSettingMe.kt
app/src/main/java/io/github/qauxv/tlb/PlayQQConfigTable.kt
app/src/main/java/me/hd/hook/HideChatPanelBtn.kt
app/src/main/java/xyz/nextalone/hook/SimplifyEmoPanel.kt
app/src/main/java/xyz/nextalone/hook/SimplifyPlusPanel.kt
app/src/main/java/xyz/nextalone/hook/SimplifyRecentDialog.kt

Fixed some things on QQ 8.2.11

---

app/src/main/java/me/hd/hook/ChangeGroupStatus.kt

Make it able to unlock almost all actions in abnormal groups.

Enhance ChangeGroupStatus on QQ 9.1.50+

---

app/src/main/java/im/mingxi/BlockLinkInfo.kt

Makes messages with links look exactly like normal messages.

Enhance RemoveShakeAdExampleHook

---

app/src/main/java/io/github/nakixii/hook/ForceUnfoldMessages.kt

Forces folded messages to be displayed.

feat: ForceUnfoldMessages
